<a href="https://colab.research.google.com/github/thecfitz/pytorch-tutorial/blob/main/tensor_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
#reshape and view
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [4]:
#reshape if we don't know the number of elements
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
my_torch2 = my_torch2.reshape(2, -1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [6]:
#slices allow you to grab a section of your tensor. Slices work similarly to standard library
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
#when selecting elements from a tensor, you are getting a tensor of that element
my_torch3[4]

tensor(4)

In [10]:
# grab slice
my_torch4 = my_torch3.reshape(5,2)
my_torch4



tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [11]:
my_torch4[:,1] #colon references all of the row/column. In this case all rows.

tensor([1, 3, 5, 7, 9])

In [12]:
#to return the same structure
my_torch4[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])